
import "./globals.css";
import MyContext  from "@/Helper/Context";
// import Header from "@/Components/Header";
export const metadata={
   title: "Nitish's Next App",
   description:"Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        {/* <Header/> */}
        <MyContext>
          {children}
        </MyContext>
      </body>
    </html>
  );
}
